aoi_name: Worms, Germany
sensitivity_factor: 1.0
day: 170
n_routes: 500
max_distance: 2000
min_distance: 350
solar_threshold_dict:
  low: 50
  high: 90
pop_file: pop_file.tif
poi_type_list:
- bus
- primary-care
- schools
osm_timestamp: '2024-06-18'
